
title: My Resume
url: 'http://venkys.neocities.org'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Venkatesh Rao  ## put your name
title: 'GRAPHIC &amp; WEB DESIGNER'  ## your title
location: Bangalore , India


## Social Profiles
facebook: http://www.facebook.com/belur02  ## your facebook account url
twitter: http://www.twitter.com/belurvrao  ## your twitter account url
linkedin: http://www.linkedin.com/bvenkateshrao  ## your linkedin account url
dribbble: http://www.dribble.com/venkateshrao  ## you dribbble account url
foursquare: http://www.foursquare.com/venkateshrao  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.

theme: jekyll-theme-minimal
